name: .NET with Heroku Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy_to_heroku:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - name: Login to Heroku
      run: heroku login -i
    - name: Check the dir
      run: pwd
    - name: Add Heroku Git Remote make a new git repo
      run: |
        git init
        heroku git:remote -a $YOUR_HEROKU_APP_NAME
      env:
        YOUR_HEROKU_APP_NAME: ${{ secrets.YOUR_HEROKU_APP_NAME }}
    - name: Deploy to Heroku
      run: |
        git push heroku master
